### ISSUE TITLE
Skrivefeil i referanser til codelists

### ISSUE THREAD

**Issue by havardsc** [Arkitektum/UML-modellering-VU053#1]
Finner en del feil referanser til kodelister i skjemaene. Ser ut som det bare er enkle skrivefeil

FagmodellVeg.xsd
https://raw.githubusercontent.com/Arkitektum/UML-modellering-VU053/main/codelists/fmv_MaterialBelegning.xml
https://raw.githubusercontent.com/Arkitektum/UML-modellering-VU053/main/codelists/fmv_passeringVedFerist.xml
https://raw.githubusercontent.com/Arkitektum/UML-modellering-VU053/main/codelists/fmv_Steinstørrelse.xml
https://raw.githubusercontent.com/Arkitektum/UML-modellering-VU053/main/codelists/fmv_Baerlagtype.xml

FagmodellRekkverk.xsd
https://raw.githubusercontent.com/Arkitektum/UML-modellering-VU053/main/codelists/fmrek_Produktnavngodkjenning.xml

**Comment by MatiasGT** [comment]
Nå er default CodeSpace Oppdatert for disse kodelistene i 

https://github.com/Arkitektum/UML-modellering-VU053/tree/main/xsd_programtesting/v1.1_20221129
